import pytest
from httpx import AsyncClient
from fastapi import status
from httpx import ASGITransport
from app import app   # adjust import if needed


@pytest.mark.asyncio
async def test_ai_texts_score_high():
    transport = ASGITransport(app=app)
    async with AsyncClient(transport=transport, base_url="http://test") as ac:
        
        # Send ONE text (API only accepts {"text": "..."} )
        response = await ac.post("/analyze", json={
            "text": "This text is generated by an AI model and uses formal structured phrasing. "
                    "Artificial intelligence often produces predictable patterns in writing."
        })

        assert response.status_code == 200
        data = response.json()

        # AI detection should be high
        assert data["ai_rate"] > 50


@pytest.mark.asyncio
async def test_human_texts_score_low():
    transport = ASGITransport(app=app)
    async with AsyncClient(transport=transport, base_url="http://test") as ac:

        # Send ONE text (again, API only accepts {"text": "..."} )
        response = await ac.post("/analyze", json={
            "text": "bro I swear I'm just typing this normally while sitting on my bed lol "
                    "this doesn't feel like AI at all, I'm literally writing casually"
        })

        assert response.status_code == 200
        data = response.json()

        # Human detection should be low
        assert data["ai_rate"] < 40
